server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commercehub
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# Custom app info
info:
  app:
    name: CommerceHub
    version: 1.0
    developer: Rajesh

# ✅ Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.rajesh.commercehub: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"